version: "2"
services:
  api:
    container_name: photo-share-api
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    command: yarn dev
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongodb://mongo:27017/photo-share
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
  mongo:
    container_name: photo-share-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
